### ISSUE TITLE
Creating a recipe: Authentication credentials were not provided

### ISSUE THREAD

**Issue by bulburDE** [RyanNoelk/OpenEats#241] opened 2017-08-20 08:45 UTC
I cannot create a recipe because after clicking the "Submit recipe" button, the following error appears: 

`Form error! Please confirm that all the data is there.`

However, as far as I can tell all required fields are filled in. In the console the following messages are logged:
`Failed to load resource: the server responded with a status of 401 (Unauthorized)` 
[authentication_credentials_not_provided.txt](https://github.com/RyanNoelk/OpenEats/files/1236962/authentication_credentials_not_provided.txt)

`Error: Unauthorized` 
[unauthorized.txt](https://github.com/RyanNoelk/OpenEats/files/1236963/unauthorized.txt)

`Authentication credentials were not provided.` [failed_to_load_resource.txt](https://github.com/RyanNoelk/OpenEats/files/1236964/failed_to_load_resource.txt)

After reloading the page, filling in and submitting the data again, the recipe is saved successfully.

Used Browser: firefox or chromium

**Comment by RyanNoelk** [comment] 2017-08-20 14:18
I'm not able to reproduce this issue. It could just be a weird token/local storage issue. Can you provide some more details who how you got to that page and when you logged-in?

You also might wanna try in a private browsing mode.

**Comment by bulburDE** [comment] 2017-08-26 23:45
The error occurred on a server where a [nginx reverse proxy](https://github.com/jwilder/nginx-proxy) for ssl encryption is configured in front of the openeats nginx. In order to rule out that this configuration is the cause for this error, I set it up on my local computer.

It can be reproduced anytime on both setups with the following steps:

1. Open the website in private browsing mode.
2. Login
3. Click on Create recipe
4. Fill in: recipe name, course, cuisine, prep time, cooking time, servings, rating, an ingredient, a direction step, recipe information
5. Click on Submit recipe
6. Above the button the following error is shown: Form error! Please confirm that all the data is there
Also the errors previously described are logged in the console.
7. Click on Submit recipe
8. The same errors are shown and logged again.
9. Reload page
10. Fill in the same information again
11. Click on Submit recipe
12. The recipe is saved successfully.

I noticed that when the saving fails the following part is missing in the http request header:
`Authorization: "Token fac0577a795dab8b6215ab57e6a2c1a1d4bbd362"


![openeats_auth_error](https://user-images.githubusercontent.com/6855903/29745940-5a38d6ea-8ac9-11e7-8d52-9e060216d3b6.png)
`

**Comment by RyanNoelk** [comment] 2017-08-27 01:21
Thanks for the detailed report. From what you are showing above, for whatever reason, the auth token isn't getting submitted along with the rest of the data. Which is weird. When a user is logged in, the auth token should be getting submitted alone with EVERY request. Meaning if the login failed for whatever reason, a user shouldn't be able to see any data due to a 401 error.

Anyways, I'm now able to replicate and will look into the issue.

**Comment by RyanNoelk** [comment] 2017-08-27 17:00
Looks like the code was creating one and only one instance of a request object. This was causing the token to never be appended to the request. And also why refreshing the page "fixed" the issue, as a new instance was getting created.

#247 Fixes this issue by create a new request instance every time we query the backend. I'll update this ticket once I've done a bit more testing and merge the PR.

**Comment by RyanNoelk** [comment] 2017-08-30 04:10
The code has been merged and master is updated with the fix. Feel free to put the latest. 

Reopen if you are still having an issue.

**Closed by RyanNoelk** 2017-08-30 04:10 UTC
